/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.programas;

import java.awt.Image;
import ventanas.personal.VentanaBajaManager;
import ventanas.personal.VentanaModificarManager;
import ventanas.reportes.ventanaReporteMovimiento;
import ventanas.personal.VentanaAltaManager;
import ventanas.areas.*;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import modelo.Sistema;
import persistencia.ArchivoGuardar;
import ventanas.personal.VentanaAdministrarEmpleados;

import ventanas.reportes.VentanaReporteAreas;

import ventanas.reportes.VentanaReporteInteligente;


/**
 *
 * @author Byakogollo
 */
public class VentanaPrincipalSistemaResumido extends javax.swing.JFrame {
    private Sistema modelo;
    
    /**
     * Creates new form VentanaSistemaNuevo
     */
    public VentanaPrincipalSistemaResumido(Sistema modelo) {
        this.modelo = modelo;
        this.setTitle("ERP Empresarial");
        initComponents();
    }

 
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        bmnAreas = new javax.swing.JMenu();
        imnAltaAreas = new javax.swing.JMenuItem();
        imnBajaAreas = new javax.swing.JMenuItem();
        imnModificacionAreas = new javax.swing.JMenuItem();
        imnMovimientoAreas = new javax.swing.JMenuItem();
        bmnManagers = new javax.swing.JMenu();
        imnAltaManagers = new javax.swing.JMenuItem();
        imnBajaManagers = new javax.swing.JMenuItem();
        imnModificacionManagers = new javax.swing.JMenuItem();
        bmnEmpleados = new javax.swing.JMenu();
        imnAltaEmpleados = new javax.swing.JMenuItem();
        bmnReportes = new javax.swing.JMenu();
        imnReporteInteligente = new javax.swing.JMenuItem();
        imnReporteEstadoAreas = new javax.swing.JMenuItem();
        imnReporteMovimientos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        lblBackground.setText("background");
        lblBackground.setMaximumSize(new java.awt.Dimension(0, 0));
        lblBackground.setMinimumSize(new java.awt.Dimension(0, 0));
        lblBackground.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 400, 280);
        ImageIcon background = new ImageIcon("./img/background.jpg"); 

        Image img = background.getImage(); 

        Image newImg = img.getScaledInstance(400,300,java.awt.Image.SCALE_SMOOTH);

        background = new ImageIcon(newImg); 

        lblBackground.setIcon(background);

        bmnAreas.setText("Areas");

        imnAltaAreas.setText("Alta");
        imnAltaAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnAltaAreasActionPerformed(evt);
            }
        });
        bmnAreas.add(imnAltaAreas);

        imnBajaAreas.setText("Baja");
        imnBajaAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnBajaAreasActionPerformed(evt);
            }
        });
        bmnAreas.add(imnBajaAreas);

        imnModificacionAreas.setText("Modificacion");
        imnModificacionAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnModificacionAreasActionPerformed(evt);
            }
        });
        bmnAreas.add(imnModificacionAreas);

        imnMovimientoAreas.setText("Realizar Movimiento");
        imnMovimientoAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnMovimientoAreasActionPerformed(evt);
            }
        });
        bmnAreas.add(imnMovimientoAreas);

        jMenuBar1.add(bmnAreas);

        bmnManagers.setText("Managers");

        imnAltaManagers.setText("Alta");
        imnAltaManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnAltaManagersActionPerformed(evt);
            }
        });
        bmnManagers.add(imnAltaManagers);

        imnBajaManagers.setText("Baja");
        imnBajaManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnBajaManagersActionPerformed(evt);
            }
        });
        bmnManagers.add(imnBajaManagers);

        imnModificacionManagers.setText("Modificacion");
        imnModificacionManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnModificacionManagersActionPerformed(evt);
            }
        });
        bmnManagers.add(imnModificacionManagers);

        jMenuBar1.add(bmnManagers);

        bmnEmpleados.setText("Empleados");

        imnAltaEmpleados.setText("Alta");
        imnAltaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnAltaEmpleadosActionPerformed(evt);
            }
        });
        bmnEmpleados.add(imnAltaEmpleados);

        jMenuBar1.add(bmnEmpleados);

        bmnReportes.setText("Reportes");

        imnReporteInteligente.setText("Reporte Inteligente");
        imnReporteInteligente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnReporteInteligenteActionPerformed(evt);
            }
        });
        bmnReportes.add(imnReporteInteligente);

        imnReporteEstadoAreas.setText("Reporte Estado de Areas");
        imnReporteEstadoAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnReporteEstadoAreasActionPerformed(evt);
            }
        });
        bmnReportes.add(imnReporteEstadoAreas);

        imnReporteMovimientos.setText("Reporte de Movimientos");
        imnReporteMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imnReporteMovimientosActionPerformed(evt);
            }
        });
        bmnReportes.add(imnReporteMovimientos);

        jMenuBar1.add(bmnReportes);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imnAltaAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnAltaAreasActionPerformed
        VentanaAltaArea alta = new VentanaAltaArea(this, true, this.modelo);
        alta.setBounds(0,0, 500, 600);
        alta.setLocationRelativeTo(this);
        alta.setVisible(true);
    }//GEN-LAST:event_imnAltaAreasActionPerformed

    private void imnModificacionAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnModificacionAreasActionPerformed
      
        
        if(!this.modelo.getAreas().isEmpty()){
                    
        VentanaModificarDescripcion modificar = new VentanaModificarDescripcion(this,true,this.modelo);
        modificar.setBounds(0,0,900,500);
        modificar.setLocationRelativeTo(this);
        modificar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No hay areas registradas", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_imnModificacionAreasActionPerformed

    private void imnBajaAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnBajaAreasActionPerformed
       
        if(!this.modelo.listarAreasSinEmpleados().isEmpty()){
            
        
        VentanaBajaArea baja = new VentanaBajaArea(this, true, this.modelo);
        baja.setBounds(0,0,800,400);
        baja.setLocationRelativeTo(this);
        baja.setVisible(true);
        
        }else{
            JOptionPane.showMessageDialog(null, "No hay areas sin empleados","Error",JOptionPane.ERROR_MESSAGE);
        
    }
        
    }//GEN-LAST:event_imnBajaAreasActionPerformed

    private void imnAltaManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnAltaManagersActionPerformed
        VentanaAltaManager alta = new VentanaAltaManager(this, true ,this.modelo);
         alta.setBounds(0,0,500,700);
        alta.setLocationRelativeTo(this);
        alta.setVisible(true);
    }//GEN-LAST:event_imnAltaManagersActionPerformed

    private void imnBajaManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnBajaManagersActionPerformed
       
        if(!this.modelo.getManagers().isEmpty()){
            
                VentanaBajaManager baja = new VentanaBajaManager(this, true ,this.modelo);
         baja.setBounds(0,0,800,400);
        baja.setLocationRelativeTo(this);
        baja.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No hay managers registrados","Error",JOptionPane.ERROR_MESSAGE);
        
    }
    }//GEN-LAST:event_imnBajaManagersActionPerformed

    private void imnModificacionManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnModificacionManagersActionPerformed
             if(!this.modelo.getManagers().isEmpty()){
            
                VentanaModificarManager modif = new VentanaModificarManager(this, true ,this.modelo);
        modif.setBounds(0,0,800,800);
        modif.setLocationRelativeTo(this);
        modif.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No hay managers registrados","Error",JOptionPane.ERROR_MESSAGE);
        
    
    }  
    }//GEN-LAST:event_imnModificacionManagersActionPerformed

    private void imnReporteInteligenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnReporteInteligenteActionPerformed
       
        VentanaReporteInteligente v = new VentanaReporteInteligente(this,true,this.modelo);
        v.setBounds(0,0,657,800);
        v.setLocationRelativeTo(this);
        v.setVisible(true);
        
    }//GEN-LAST:event_imnReporteInteligenteActionPerformed

    private void imnReporteEstadoAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnReporteEstadoAreasActionPerformed
        VentanaReporteAreas v = new VentanaReporteAreas(this,true,this.modelo);
        v.setBounds(0, 0, 656, 580);
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }//GEN-LAST:event_imnReporteEstadoAreasActionPerformed

    private void imnReporteMovimientosActionPerformed(java.awt.event.ActionEvent evt)  {                                                      
        ventanaReporteMovimiento ventanaReporteArea = new ventanaReporteMovimiento(null, rootPaneCheckingEnabled, modelo);
        ventanaReporteArea.setBounds(0,0,900,500);
        ventanaReporteArea.setLocationRelativeTo(this);
        ventanaReporteArea.setVisible(true);
        
    }


    private void imnAltaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnAltaEmpleadosActionPerformed
              
            if(!this.modelo.getAreas().isEmpty() && !this.modelo.getManagers().isEmpty()){
                
            
                VentanaAdministrarEmpleados modif = new VentanaAdministrarEmpleados(this, true ,this.modelo);
        modif.setBounds(0,0,650,650);
        modif.setLocationRelativeTo(this);
        modif.setVisible(true);
        }else{
                JOptionPane.showMessageDialog(null, "No se pueden ingresar empleados si no hay managers y areas registradas", "Error",JOptionPane.ERROR_MESSAGE);
            }
            
    }//GEN-LAST:event_imnAltaEmpleadosActionPerformed

    private void imnMovimientoAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imnMovimientoAreasActionPerformed
           if(!this.modelo.getAreas().isEmpty()){
            
        
        VentanaRealizarMovimiento mov = new VentanaRealizarMovimiento(this, true, this.modelo);
        mov.setBounds(0,0,511,774);
        mov.setLocationRelativeTo(this);
        mov.setVisible(true);
        
        }else{
            JOptionPane.showMessageDialog(null, "No hay areas sin empleados","Error",JOptionPane.ERROR_MESSAGE);
        
    }
       
    }//GEN-LAST:event_imnMovimientoAreasActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
         boolean guardarSistema = new ArchivoGuardar().guardarSistema(this.modelo);
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bmnAreas;
    private javax.swing.JMenu bmnEmpleados;
    private javax.swing.JMenu bmnManagers;
    private javax.swing.JMenu bmnReportes;
    private javax.swing.JMenuItem imnAltaAreas;
    private javax.swing.JMenuItem imnAltaEmpleados;
    private javax.swing.JMenuItem imnAltaManagers;
    private javax.swing.JMenuItem imnBajaAreas;
    private javax.swing.JMenuItem imnBajaManagers;
    private javax.swing.JMenuItem imnModificacionAreas;
    private javax.swing.JMenuItem imnModificacionManagers;
    private javax.swing.JMenuItem imnMovimientoAreas;
    private javax.swing.JMenuItem imnReporteEstadoAreas;
    private javax.swing.JMenuItem imnReporteInteligente;
    private javax.swing.JMenuItem imnReporteMovimientos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
