/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas.reportes;

import javax.swing.table.DefaultTableModel;

import modelo.Area;
import modelo.Empleado;
import modelo.Movimiento;
import modelo.Sistema;

/**
 *
 * @author esteb
 */
public class ventanaReporteArea extends javax.swing.JDialog {
    private Sistema modelo;

    /**
     * Creates new form ventanaReporteArea
     */
    public ventanaReporteArea(java.awt.Frame parent, boolean modal, Sistema modelo) {
        super(parent, modal);
        initComponents();
        this.modelo = modelo;
        this.cargarTabla();
        this.setLocationRelativeTo(null);
    }

    private void cargarTabla() {

        javax.swing.table.DefaultTableModel tabla = (javax.swing.table.DefaultTableModel) this.jTable2.getModel();

        // Limpiar la tabla
        tabla.setRowCount(0);

        java.util.ArrayList<Movimiento> lista = this.modelo.listarMovimientosPorMesAsc();

        int i = 0;
        while (i < lista.size()) {
            Movimiento mov = lista.get(i);

            int mes = mov.getMes();
            Area origen = mov.getOrigen();
            Area destino = mov.getDestino();
            Empleado emp = mov.getEmpleado();

            String nomOri = (origen == null) ? "-" : origen.getNombre();
            String nomDes = (destino == null) ? "-" : destino.getNombre();
            String nomEmp = (emp == null) ? "-" : (emp.getNombre() + " (" + emp.getCi() + ")");

            tabla.addRow(new Object[] {
                    mes,
                    nomOri,
                    nomDes,
                    nomEmp
            });

            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        cerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Reporte Movimientos por Area");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Mes", "Area Origen", "Area Destino", "Empleado"
                }));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(189, 189, 189)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(240, 240, 240)
                                                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(190, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53,
                                        Short.MAX_VALUE)
                                .addComponent(cerrar)
                                .addGap(39, 39, 39)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
    }// GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
