/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas.reportes;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import javax.swing.ListSelectionModel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

import modelo.Area;
import modelo.Empleado;

import modelo.Sistema;

/**
 *
 * @author esteb
 */
public class VentanaReporteAreas extends javax.swing.JDialog {
    private Sistema modelo;
    private ArrayList<Area> cacheAreas;
    
    
    /**
     * Creates new form ReporteArea
     */
    public VentanaReporteAreas(java.awt.Frame parent, boolean modal, Sistema modelo) {
        super(parent, modal);
        initComponents();

        this.modelo = modelo;
        

        this.lblDetalle.setText("Detalles del Area");

        this.tblAreas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        this.pnlBotones.setLayout(new GridBagLayout());

        
        this.cargarTabla();
        

    }
    
    private void cargarTabla(){
       
        ArrayList<Area> areasOrdenadas = this.cargarAreasOrdenadasPorPorcentajeDesc();
       
        DefaultTableModel table = (DefaultTableModel) tblAreas.getModel();
                
        table.setRowCount(0);
                
                   
                
                for (Area area : areasOrdenadas) {
                        table.addRow(new Object[]{ area.getNombre() });
                    }
                
        
                     TableCellRenderer renderer = new DefaultTableCellRenderer(){
              
                        @Override
                          public Component getTableCellRendererComponent(JTable table, Object value,
                          boolean isSelected, boolean hasFocus, int row, int column) {

                              Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                                      double porcentajeAsignado = calcularPorcentajeAsignado(areasOrdenadas.get(row));

                                      if (porcentajeAsignado > 90.0) {
                                          c.setBackground(Color.RED);
                                          c.setForeground(Color.WHITE);
                                      } else if(porcentajeAsignado > 70.0 && porcentajeAsignado <=90.0){
                                          c.setBackground(Color.YELLOW);
                                          c.setForeground(Color.BLACK);
                                      }else{
                                          c.setBackground(Color.WHITE);
                                          c.setForeground(Color.BLACK);
                                      }

                                      return c;
                                  }
                              };

                           tblAreas.getColumnModel().getColumn(0).setCellRenderer(renderer);

                            
    }
    

   private ArrayList<Area> cargarAreasOrdenadasPorPorcentajeDesc() {
    ArrayList<Area> resultado = new ArrayList<>(this.modelo.getAreas());

   
    resultado.sort((a1, a2) -> Double.compare(calcularPorcentajeAsignado(a2), calcularPorcentajeAsignado(a1)));

    return resultado;
}


    private double calcularPorcentajeAsignado(Area a) {
      
        double pct = (a.salarioAnualAsignado() * 100.0) / a.getPresupuestoAnual();
     
        return pct;
    }

    private double redondear2(double v) {
        return Math.round(v * 100.0) / 100.0;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void generarBotones(Empleado emp, int index){
        
        JButton btnEmpleado = new JButton(emp.getNombre());
              
        btnEmpleado.setPreferredSize(new Dimension(100,30));
        
        
        
        btnEmpleado.setBackground(new Color(0,0,this.modelo.calcularColor(emp)));
       
        
        btnEmpleado.setBorder(new LineBorder(Color.BLACK,1,true));
        btnEmpleado.setForeground(Color.white);
       
        btnEmpleado.addActionListener(e-> {
            
            VentanaInfoEmpleado v = new VentanaInfoEmpleado(null,true,this.modelo,emp);
            v.setBounds(0,0,350,500);
            v.setLocationRelativeTo(this);
            v.setVisible(true);
            
            
        });                
         
        
        GridBagConstraints gridPanel = new GridBagConstraints();
        gridPanel.gridx = index % 3;
        gridPanel.gridy = index / 3;
        
        
        
        gridPanel.insets = new Insets(5,5,5,5);
        gridPanel.fill = GridBagConstraints.NONE;
        
        gridPanel.anchor = GridBagConstraints.NORTHWEST;
        gridPanel.weightx = 0;
        gridPanel.weighty = 0;
     
        
        this.pnlBotones.add(btnEmpleado,gridPanel);
        this.pnlBotones.revalidate();
        this.pnlBotones.repaint();
        
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        lblTitulo = new javax.swing.JLabel();
        lblDetalle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAreas = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        lblArea = new javax.swing.JLabel();
        lblPresupuesto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTitulo.setText("Estado de Areas");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(190, 20, 280, 48);

        lblDetalle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDetalle.setText("Detalle");
        lblDetalle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblDetalle);
        lblDetalle.setBounds(260, 260, 360, 30);

        tblAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Areas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAreas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAreasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAreas);
        if (tblAreas.getColumnModel().getColumnCount() > 0) {
            tblAreas.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 90, 170, 310);

        pnlBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlBotones.setLayout(null);
        getContentPane().add(pnlBotones);
        pnlBotones.setBounds(260, 90, 360, 160);

        lblArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblArea.setText("Area Seleccionada:");
        getContentPane().add(lblArea);
        lblArea.setBounds(260, 300, 360, 30);

        lblPresupuesto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPresupuesto.setText("Presupuesto Usado:");
        getContentPane().add(lblPresupuesto);
        lblPresupuesto.setBounds(260, 340, 360, 30);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 400, 130, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAreasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAreasMouseClicked
        DefaultTableModel table = (DefaultTableModel) tblAreas.getModel();
        
        Area seleccion = this.modelo.buscarAreaPorNombre((String)table.getValueAt(this.tblAreas.getSelectedRow(),0));
        this.lblDetalle.setText("Detalles del Area");
        this.lblArea.setText("Area Seleccionada: "+seleccion.getNombre());
        this.lblPresupuesto.setText("Presupuesto Usado: "+this.calcularPorcentajeAsignado(seleccion)+"%");
        
        this.pnlBotones.removeAll();
        this.pnlBotones.revalidate();
        this.pnlBotones.repaint();
        
        ArrayList<Empleado> listaOrdenadaPorNombre = new ArrayList<>(seleccion.getEmpleados());
        listaOrdenadaPorNombre.sort((a1,a2) -> a1.getNombre().compareTo(a2.getNombre()));
        
        for (int i =0; i<listaOrdenadaPorNombre.size();i++){
            
            
            this.generarBotones(listaOrdenadaPorNombre.get(i), i);
        }
        
       
        
    }//GEN-LAST:event_tblAreasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblPresupuesto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JTable tblAreas;
    // End of variables declaration//GEN-END:variables
}
