/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas.reportes;

import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import modelo.Area;
import modelo.Empleado;
import modelo.ExcepcionesSistema;
import modelo.Gemini;
import modelo.Sistema;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Byakogollo
 */
public class VentanaReporteInteligente extends javax.swing.JDialog {
        private Sistema modelo;
    /**
     * Creates new form VentanaRealizarMovimiento
     */
    public VentanaReporteInteligente(java.awt.Frame parent, boolean modal, Sistema modelo) {
        super(parent, modal);
        this.modelo = modelo;
        initComponents();
        
        
         
         
        this.lblGatito.setVisible(false);
        this.lstAreaOrigen.setListData(this.modelo.getAreas().toArray(new Area[0]));
    }
    
  
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        lblEmpleado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmpleados = new javax.swing.JList<>();
        lblArea = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAreaOrigen = new javax.swing.JList<>();
        lblDestino = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstAreaDestino = new javax.swing.JList<>();
        btnCancelar = new javax.swing.JButton();
        btnGenerarReporte = new javax.swing.JButton();
        pnlTextArea = new javax.swing.JScrollPane();
        txtGemini = new javax.swing.JTextArea();
        lblGatito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Reporte Inteligente");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(160, 30, 340, 90);

        lblMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMes.setText("Seleccione el mes");
        getContentPane().add(lblMes);
        lblMes.setBounds(160, 150, 110, 20);

        cmbMes.setMaximumRowCount(12);
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(cmbMes);
        cmbMes.setBounds(370, 150, 110, 20);

        lblEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmpleado.setText("Seleccione empleado");
        getContentPane().add(lblEmpleado);
        lblEmpleado.setBounds(120, 340, 140, 20);

        lstEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstEmpleados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 370, 330, 100);

        lblArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblArea.setText("Seleccione el area de origen");
        getContentPane().add(lblArea);
        lblArea.setBounds(100, 200, 190, 20);

        lstAreaOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAreaOrigenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstAreaOrigen);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 230, 330, 100);

        lblDestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDestino.setText("Seleccione el area de destino");
        getContentPane().add(lblDestino);
        lblDestino.setBounds(100, 490, 190, 20);

        jScrollPane3.setViewportView(lstAreaDestino);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 520, 330, 100);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(110, 650, 180, 70);

        btnGenerarReporte.setText("Generar Reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarReporte);
        btnGenerarReporte.setBounds(370, 650, 180, 70);

        txtGemini.setEditable(false);
        txtGemini.setColumns(20);
        txtGemini.setRows(1);
        txtGemini.setText("Hola, quieres que te genere un reporte?");
        pnlTextArea.setViewportView(txtGemini);

        getContentPane().add(pnlTextArea);
        pnlTextArea.setBounds(390, 230, 240, 30);
        getContentPane().add(lblGatito);
        lblGatito.setBounds(400, 270, 200, 350);
        ImageIcon icono = new ImageIcon("./img/gatito.gif");

        lblGatito.setIcon(icono);

        lblGatito.setHorizontalAlignment(SwingConstants.CENTER);
        lblGatito.setVerticalAlignment(SwingConstants.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         JOptionPane alerta = new JOptionPane();
       int seleccion = alerta.showConfirmDialog(this,"Desea cancelar?", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
       
       if(seleccion == alerta.YES_OPTION){
           this.dispose();
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lstAreaOrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAreaOrigenMouseClicked
        Area a = (Area)this.lstAreaOrigen.getSelectedValue();        
        this.lstEmpleados.setListData(this.modelo.getEmpleadosPorArea(a).toArray(new Empleado[0]));
        
      
    }//GEN-LAST:event_lstAreaOrigenMouseClicked

    private void lstEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEmpleadosMouseClicked
         if(this.lstEmpleados.getSelectedIndex() >= 0 ){
            Empleado e = (Empleado)this.lstEmpleados.getSelectedValue();
            this.lstAreaDestino.setListData(this.modelo.listarAreasQueNoTenganEmpleado(e).toArray(new Area[0]));
        }
    }//GEN-LAST:event_lstEmpleadosMouseClicked

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
               
        
        
        try{
                 
        Area origen = (Area) this.lstAreaOrigen.getSelectedValue();
        if(origen == null) throw new ExcepcionesSistema("Seleccione un area de origen para el reporte inteligente");
        Empleado emp = (Empleado) this.lstEmpleados.getSelectedValue();
        if(emp == null) throw new ExcepcionesSistema("Seleccione un empleado para el reporte inteligente");
        Area destino = (Area) this.lstAreaDestino.getSelectedValue();
        if(destino == null) throw new ExcepcionesSistema("Seleccione un area de destino para el reporte inteligente");
        int mes = Integer.parseInt((String)this.cmbMes.getSelectedItem());   
        
        this.lblGatito.setVisible(true);
        
        this.revalidate();
        this.repaint();
        
        this.btnGenerarReporte.setEnabled(false);
      
        
            
       
            new Thread(() -> {
            try {
                Gemini gemini = new Gemini();
                
                String respuesta = gemini.pedirReporte(
                        origen.getNombre(),
                        origen.getPresupuestoAnual(),
                        emp.getNombre(),
                        emp.getSalarioMensual(),
                        mes,
                        destino.getNombre(),
                        destino.getPresupuestoAnual()
                );

                
                SwingUtilities.invokeLater(() -> {
                    txtGemini.setText(respuesta);
                    
                    
                    lblGatito.setVisible(false);
                    btnGenerarReporte.setEnabled(true);
                    this.txtGemini.setLineWrap(true);
                    this.txtGemini.setWrapStyleWord(true);
                    this.pnlTextArea.setSize(new Dimension(212,300));
                    
                    
                    System.out.println("actualizo hilo"); // debug
                });

            } catch (ExcepcionesSistema ex) {
                
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(
                            this,
                            "Error: " + ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                    lblGatito.setVisible(false);
                    btnGenerarReporte.setEnabled(true);
                    System.out.println("catch 2");
                });
                
            } catch (Exception ex) {
                
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(
                            this,
                            "Error al llamar a Gemini: " + ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                    lblGatito.setVisible(false);
                    btnGenerarReporte.setEnabled(true);
                    System.out.println("catch 3");
                });
                
            }
            
        }).start();
            
            
            
        }catch(ExcepcionesSistema ex){
            JOptionPane.showMessageDialog(null, "Error: "+ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
         //debug
         System.out.println("cierro gato");
        
        
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblGatito;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<Area> lstAreaDestino;
    private javax.swing.JList<Area> lstAreaOrigen;
    private javax.swing.JList<Empleado> lstEmpleados;
    private javax.swing.JScrollPane pnlTextArea;
    private javax.swing.JTextArea txtGemini;
    // End of variables declaration//GEN-END:variables
}
