/*
TRABAJO REALIZADO POR ESTEBAN NECUSE 227582 Y MARCOS MEDINA 365070
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas.inicializacion;

import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.JOptionPane;
import modelo.Sistema;
import persistencia.ArchivoCargar;

import ventanas.programas.VentanaPrincipalDemoSistema;
import ventanas.programas.VentanaPrincipalSistemaNuevo;
import ventanas.programas.VentanaPrincipalSistemaResumido;

/**
 *
 * @author jacqu
 */
public class VentanaInicial extends javax.swing.JFrame {

    private Sistema modelo;

    public VentanaInicial(Sistema modelo) {
        initComponents();
        setTitle("ERP - Inicio");
        setLocationRelativeTo(null);
        this.modelo = modelo;

        java.awt.event.KeyAdapter listenerF1 = new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_F1) {
                    llamarIntegrantes();
                }
            }
        };

      
        btnDemoSistema.addKeyListener(listenerF1);
        btnSistemaNuevo.addKeyListener(listenerF1);
        btnResumirSistema.addKeyListener(listenerF1);
    }

    private void llamarIntegrantes() {

        VentanaIntegrantes v = new VentanaIntegrantes();
        v.setLocationRelativeTo(this);
        v.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnDemoSistema = new javax.swing.JButton();
        btnSistemaNuevo = new javax.swing.JButton();
        btnResumirSistema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VentanaInicial");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Inicializacion");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(210, 30, 260, 40);

        btnDemoSistema.setText("Demo del Sistema");
        btnDemoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemoSistemaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDemoSistema);
        btnDemoSistema.setBounds(420, 110, 170, 40);

        btnSistemaNuevo.setText("Nuevo Sistema");
        btnSistemaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSistemaNuevo);
        btnSistemaNuevo.setBounds(40, 110, 170, 40);

        btnResumirSistema.setText("Resumir Sistema");
        btnResumirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumirSistemaActionPerformed(evt);
            }
        });
        getContentPane().add(btnResumirSistema);
        btnResumirSistema.setBounds(230, 110, 170, 40);

        setBounds(0, 0, 646, 232);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDemoSistemaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDemoSistemaActionPerformed
        VentanaPrincipalDemoSistema ventana = new VentanaPrincipalDemoSistema(this.modelo);
        ventana.setBounds(0, 0, 400, 300);
        ventana.setLocationRelativeTo(this);

        ventana.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_btnDemoSistemaActionPerformed

    private void btnResumirSistemaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResumirSistemaActionPerformed

        try {

            String basePath = System.getProperty("user.dir") + "/persistencia";
            File file = new File(basePath + "/Sistema");
            System.out.println(basePath);

            if (!file.exists()) {

                JOptionPane.showMessageDialog(null,
                        "Error al cargar el sistema. Asegurese que el sistema haya sido guardado anteriormente",
                        "Error", JOptionPane.ERROR_MESSAGE);

            } else {

                Sistema modeloCargado = new ArchivoCargar().cargarSistema();

                VentanaPrincipalSistemaResumido ventanaResumida = new VentanaPrincipalSistemaResumido(modeloCargado);
                ventanaResumida.setBounds(0, 0, 400, 300);
                ventanaResumida.setLocationRelativeTo(this);

                ventanaResumida.setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {

            System.out.println("Error" + e);

        }

    }// GEN-LAST:event_btnResumirSistemaActionPerformed

    private void btnSistemaNuevoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSistemaNuevoActionPerformed
        VentanaPrincipalSistemaNuevo ventana = new VentanaPrincipalSistemaNuevo(this.modelo);

        ventana.setBounds(0, 0, 400, 300);
        ventana.setLocationRelativeTo(this);

        ventana.setVisible(true);

        this.dispose();

    }// GEN-LAST:event_btnSistemaNuevoActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here: this.setFocusable(true);

        this.requestFocusInWindow();
        if (evt.getKeyCode() == KeyEvent.VK_F1) {

        }
    }// GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDemoSistema;
    private javax.swing.JButton btnResumirSistema;
    private javax.swing.JButton btnSistemaNuevo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
