/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas.personal;


import ventanas.areas.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Area;
import modelo.ExcepcionesSistema;
import modelo.Manager;

import modelo.Sistema;

/**
 *
 * @author Byakogollo
 */
public class VentanaAltaEmpleado extends javax.swing.JDialog {
    private Sistema modelo;
    /**
     * Creates new form VentanaAltaArea
     */
    public VentanaAltaEmpleado(){
        initComponents();
    }
    public VentanaAltaEmpleado(java.awt.Dialog parent, boolean modal, Sistema modelo) {
       super(parent, modal);
       this.modelo = modelo;
       
        initComponents();
        
        this.lstManagers.setListData(this.modelo.getManagers().toArray(new Manager[0]));
   
        
        this.cargarTabla();
       
        
        
    }
    
       private void cargarTabla(){
                      
                
               
                DefaultTableModel table = (DefaultTableModel) tblAreas.getModel();
                table.setRowCount(0);
                                
                for(int i = 0; i<this.modelo.getAreas().size();i++){
                                
                table.insertRow(0,new Object[] {
                   this.modelo.getAreas().get(i).getNombre(),
                   this.modelo.getAreas().get(i).getPresupuestoAnual(),
                });
                
                }
                
                
                
       
    }

       
             
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblManagers = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAgregarEmpleado = new javax.swing.JButton();
        spnCedula = new javax.swing.JSpinner();
        lblCelular = new javax.swing.JLabel();
        spnSalario = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstManagers = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAreas = new javax.swing.JTable();
        lblManagers1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCurriculum = new javax.swing.JTextArea();
        lblCurriculum1 = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        spnCelular1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Alta Empleado");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(190, 20, 244, 80);

        lblCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCedula.setText("Cedula");
        getContentPane().add(lblCedula);
        lblCedula.setBounds(250, 200, 120, 20);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(250, 160, 50, 20);

        lblManagers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblManagers.setText("Areas");
        getContentPane().add(lblManagers);
        lblManagers.setBounds(50, 460, 70, 20);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(380, 670, 220, 50);

        btnAgregarEmpleado.setText("Agregar Empleado");
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarEmpleado);
        btnAgregarEmpleado.setBounds(50, 670, 220, 50);
        getContentPane().add(spnCedula);
        spnCedula.setBounds(400, 200, 210, 22);

        lblCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCelular.setText("Celular");
        getContentPane().add(lblCelular);
        lblCelular.setBounds(250, 240, 90, 20);

        spnSalario.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spnSalario);
        spnSalario.setBounds(400, 390, 210, 22);

        lstManagers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstManagersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstManagers);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 150, 170, 270);

        tblAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Presupuesto Restante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAreas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 490, 570, 130);

        lblManagers1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblManagers1.setText("Managers");
        getContentPane().add(lblManagers1);
        lblManagers1.setBounds(90, 130, 70, 20);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(400, 160, 210, 22);

        txtCurriculum.setColumns(20);
        txtCurriculum.setRows(5);
        jScrollPane3.setViewportView(txtCurriculum);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(400, 280, 210, 90);

        lblCurriculum1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCurriculum1.setText("Curriculum");
        getContentPane().add(lblCurriculum1);
        lblCurriculum1.setBounds(250, 310, 90, 20);

        lblSalario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSalario.setText("Salario");
        getContentPane().add(lblSalario);
        lblSalario.setBounds(250, 390, 90, 20);

        spnCelular1.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spnCelular1);
        spnCelular1.setBounds(400, 240, 210, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        
            try{    
                
        if(this.txtNombre.getText().trim().isBlank()){
            throw new ExcepcionesSistema("Ingrese un nombre");
        }else if (this.txtCurriculum.getText().trim().isBlank()){
            throw new ExcepcionesSistema("Ingrese un curriculum");
        }else if ((Integer)this.spnCedula.getValue() <= 0 || (Integer) this.spnSalario.getValue() <= 0){
            throw new ExcepcionesSistema("La cedula y el celular no pueden ser 0");
        }else if(this.tblAreas.getSelectedRow() < 0){
            throw new ExcepcionesSistema("Seleccione un area");
        }else if(this.lstManagers.getSelectedIndex() < 0){
            throw new ExcepcionesSistema("Seleccione un manager");
        }            

            
            }catch(ExcepcionesSistema e){    
                JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
}

  try{
                    if(this.modelo.altaEmpleado(this.txtNombre.getText(), (Integer) this.spnCedula.getValue(), (Integer)this.spnSalario.getValue(), this.txtCurriculum.getText(),
                       Double.valueOf((Integer)this.spnSalario.getValue()), (Manager)this.lstManagers.getSelectedValue(),
                       this.modelo.buscarAreaPorNombre((String)this.tblAreas.getValueAt(this.tblAreas.getSelectedRow(),0)))){
                                   
                       JOptionPane.showMessageDialog(null, "Empleado guardado con exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
                              
                        this.dispose();
                
                    }
                }catch(ExcepcionesSistema e){
                     
                    JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);

                        }
                
                
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
          JOptionPane alerta = new JOptionPane();
       int seleccion = alerta.showConfirmDialog(this,"Desea salir?", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
       
       if(seleccion == alerta.YES_OPTION){
           this.dispose();
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lstManagersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstManagersMouseClicked
            
    }//GEN-LAST:event_lstManagersMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCurriculum1;
    private javax.swing.JLabel lblManagers;
    private javax.swing.JLabel lblManagers1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<Manager> lstManagers;
    private javax.swing.JSpinner spnCedula;
    private javax.swing.JSpinner spnCelular1;
    private javax.swing.JSpinner spnSalario;
    private javax.swing.JTable tblAreas;
    private javax.swing.JTextArea txtCurriculum;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
