/*
TRABAJO REALIZADO POR ESTEBAN NECUSE 227582 Y MARCOS MEDINA 365070
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas.personal;


import ventanas.areas.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ExcepcionesSistema;

import modelo.Sistema;

/**
 *
 * @author Byakogollo
 */
public class VentanaAltaManager extends javax.swing.JDialog {
    private Sistema modelo;
    /**
     * Creates new form VentanaAltaArea
     */
    public VentanaAltaManager(){
        initComponents();
    }
    public VentanaAltaManager(java.awt.Frame parent, boolean modal, Sistema modelo) {
       super(parent, modal);
       this.modelo = modelo;
       
        initComponents();
        this.updateWindow();
        
    }
    
    private void updateWindow(){
                       
               
                DefaultTableModel table = (DefaultTableModel) tblManagers.getModel();
                table.setRowCount(0);
                for(int i = 0; i<this.modelo.getManagers().size(); i++){
                                    
                
                table.insertRow(0,new Object[] {
                    this.modelo.getManagers().get(i).getNombre(),
                    this.modelo.getManagers().get(i).getCi(),
                    this.modelo.getManagers().get(i).getAntiguedad(),
                                        
                });
                
                
    }
                this.txtNombre.setText("");
                this.spnCedula.setValue(0);
                this.spnAntiguedad.setValue(0);
                this.spnCelular.setValue(0);
                this.modelo.ordenarManagersPorAntiguedadDesc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblAntiguedad = new javax.swing.JLabel();
        spnAntiguedad = new javax.swing.JSpinner();
        lblManagers = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAgregarManager = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManagers = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        spnCedula = new javax.swing.JSpinner();
        lblCelular = new javax.swing.JLabel();
        spnCelular = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Alta Manager");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(120, 20, 280, 80);

        lblCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCedula.setText("Cedula");
        getContentPane().add(lblCedula);
        lblCedula.setBounds(50, 170, 120, 20);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(50, 130, 80, 20);

        lblAntiguedad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAntiguedad.setText("Antiguedad");
        getContentPane().add(lblAntiguedad);
        lblAntiguedad.setBounds(50, 210, 90, 20);
        getContentPane().add(spnAntiguedad);
        spnAntiguedad.setBounds(190, 210, 210, 26);

        lblManagers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblManagers.setText("Managers");
        getContentPane().add(lblManagers);
        lblManagers.setBounds(40, 400, 70, 20);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(260, 320, 140, 50);

        btnAgregarManager.setText("Agregar Manager");
        btnAgregarManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarManager);
        btnAgregarManager.setBounds(70, 320, 140, 50);

        tblManagers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cedula", "Antiguedad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManagers);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 450, 410, 150);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(190, 130, 210, 24);
        getContentPane().add(spnCedula);
        spnCedula.setBounds(190, 170, 210, 26);

        lblCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCelular.setText("Celular");
        getContentPane().add(lblCelular);
        lblCelular.setBounds(50, 250, 90, 20);

        spnCelular.setModel(new javax.swing.SpinnerNumberModel());
        getContentPane().add(spnCelular);
        spnCelular.setBounds(190, 250, 210, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarManagerActionPerformed
        
       try{                  
            if(this.modelo.altaManager(this.txtNombre.getText(), (Integer) this.spnCedula.getValue(), (Integer)this.spnCelular.getValue(),(Integer)this.spnAntiguedad.getValue())){
                                
                JOptionPane.showMessageDialog(null, "Manager guardado con exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
               
                this.updateWindow();
             }           
        }catch(ExcepcionesSistema e){
      JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarManagerActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
          JOptionPane alerta = new JOptionPane();
       int seleccion = alerta.showConfirmDialog(this,"Desea salir?", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
       
       if(seleccion == alerta.YES_OPTION){
           this.dispose();
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarManager;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAntiguedad;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblManagers;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSpinner spnAntiguedad;
    private javax.swing.JSpinner spnCedula;
    private javax.swing.JSpinner spnCelular;
    private javax.swing.JTable tblManagers;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
