/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas.personal;

import ventanas.areas.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Area;
import modelo.Sistema;

/**
 *
 * @author Byakogollo
 */
public class VentanaBajaManager extends javax.swing.JDialog {
    private Sistema modelo;
    /**
     * Creates new form VentanaBajaArea
     */
    public VentanaBajaManager(java.awt.Frame parent, boolean modal, Sistema modelo) {
        super(parent, modal);
        this.modelo = modelo;
        initComponents();
        this.cargarTabla();
        
    }
    
        private void cargarTabla(){
                       
               
                DefaultTableModel table = (DefaultTableModel) tblManagers.getModel();
                table.setRowCount(0);
                for(int i = 0; i<this.modelo.getManagers().size(); i++){
                                    
                if(this.modelo.getManagers().get(i).getEmpleadosACargo().isEmpty()){
                    
                                    
                table.insertRow(0,new Object[] {
                    this.modelo.getManagers().get(i).getNombre(),
                    this.modelo.getManagers().get(i).getCi(),
                    this.modelo.getManagers().get(i).getCelular(),
                    this.modelo.getManagers().get(i).getAntiguedad(),
                                                            
                });
                }
                
    }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManagers = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Baja Manager");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(250, 30, 270, 48);

        tblManagers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Cedula", "Celular", "Antiguedad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManagers);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 480, 180);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(550, 240, 160, 80);

        btnBaja.setText("Dar de baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBaja);
        btnBaja.setBounds(550, 140, 160, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
            JOptionPane alerta = new JOptionPane();
       int seleccion = alerta.showConfirmDialog(this,"Desea salir?", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
       
       if(seleccion == alerta.YES_OPTION){
           this.dispose();
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
         DefaultTableModel tabla = (DefaultTableModel) this.tblManagers.getModel();
          int index = this.tblManagers.getSelectedRow();
           if(index >= 0){
               
          int ci = (Integer)this.tblManagers.getValueAt(index, 1);
          
                
          
          if(JOptionPane.showConfirmDialog(this, "Esta seguro que desea dar de baja al manager?", "Confirmar baja", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.YES_OPTION){
             
             
              if(this.modelo.bajaManager(ci)){
                  JOptionPane.showMessageDialog(null, "Manager dado de baja correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                   
                    this.cargarTabla();
              }
             
          }
          }else{
               JOptionPane.showMessageDialog(this, "Seleccione el manager a dar de baja","Error", JOptionPane.ERROR_MESSAGE);
           }
    }//GEN-LAST:event_btnBajaActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblManagers;
    // End of variables declaration//GEN-END:variables
}
