/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas.areas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Area;
import modelo.Sistema;

/**
 *
 * @author Byakogollo
 */
public class VentanaBajaArea extends javax.swing.JDialog {
    private Sistema modelo;
    /**
     * Creates new form VentanaBajaArea
     */
    public VentanaBajaArea(java.awt.Frame parent, boolean modal, Sistema modelo) {
        super(parent, modal);
        this.modelo = modelo;
        initComponents();
        this.cargarTabla();
    }
    
        private void cargarTabla(){
                       
               
                DefaultTableModel table = (DefaultTableModel) tblAreas.getModel();
                table.setRowCount(0);
                for(int i = 0; i<this.modelo.getAreas().size(); i++){
                                    
                if(this.modelo.getAreas().get(i).getEmpleados().isEmpty()){
                    
                                    
                table.insertRow(0,new Object[] {
                    this.modelo.getAreas().get(i).getNombre(),
                    this.modelo.getAreas().get(i).getPresupuestoAnual(),
                                                            
                });
                }
                
    }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAreas = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Baja Area");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(300, 30, 158, 48);

        tblAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre Area", "Presupuesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAreas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 140, 430, 180);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(550, 240, 160, 80);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(550, 140, 160, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         DefaultTableModel tabla = (DefaultTableModel) this.tblAreas.getModel();
          int index = this.tblAreas.getSelectedRow();
           if(index >= 0){
               
          String nom = (String)this.tblAreas.getValueAt(index, 0);
          
         
          
          
          if(JOptionPane.showConfirmDialog(this, "Esta seguro que desea eliminar el area?", "CONFIRMAR BORRAR", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.YES_OPTION){
              System.out.println("areas antes"+this.modelo.getAreas().toString());
             
              if(this.modelo.bajaArea(nom)){
                  JOptionPane.showMessageDialog(null, "Area borrada correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                   System.out.println("aras desp"+this.modelo.getAreas().toString());
                    this.cargarTabla();
              }
             
          }
          }else{
               JOptionPane.showMessageDialog(this, "Seleccione el area a eliminar","ERROR", JOptionPane.ERROR_MESSAGE);
           }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblAreas;
    // End of variables declaration//GEN-END:variables
}
