/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas.areas;

import javax.swing.JOptionPane;
import modelo.Area;
import modelo.Empleado;
import modelo.ExcepcionesSistema;
import modelo.Sistema;

/**
 *
 * @author Byakogollo
 */
public class VentanaRealizarMovimiento extends javax.swing.JDialog {
        private Sistema modelo;
    /**
     * Creates new form VentanaRealizarMovimiento
     */
    public VentanaRealizarMovimiento(java.awt.Frame parent, boolean modal, Sistema modelo) {
        super(parent, modal);
        this.modelo = modelo;
        initComponents();
        this.lstAreaOrigen.setListData(this.modelo.getAreas().toArray(new Area[0]));
    }
    
  
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        lblEmpleado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmpleados = new javax.swing.JList<>();
        lblArea = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAreaOrigen = new javax.swing.JList<>();
        lblDestino = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstAreaDestino = new javax.swing.JList<>();
        btnCancelar = new javax.swing.JButton();
        btnConfirmarMovimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Realizar Movimiento");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(90, 30, 360, 90);

        lblMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMes.setText("Seleccione el mes");
        getContentPane().add(lblMes);
        lblMes.setBounds(80, 150, 110, 16);

        cmbMes.setMaximumRowCount(12);
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(cmbMes);
        cmbMes.setBounds(330, 150, 110, 22);

        lblEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmpleado.setText("Seleccione empleado a mover");
        getContentPane().add(lblEmpleado);
        lblEmpleado.setBounds(170, 340, 190, 20);

        lstEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstEmpleados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 370, 380, 100);

        lblArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblArea.setText("Seleccione el area de origen");
        getContentPane().add(lblArea);
        lblArea.setBounds(170, 200, 190, 20);

        lstAreaOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAreaOrigenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstAreaOrigen);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 230, 380, 100);

        lblDestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDestino.setText("Seleccione el area de destino");
        getContentPane().add(lblDestino);
        lblDestino.setBounds(170, 490, 190, 20);

        jScrollPane3.setViewportView(lstAreaDestino);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(70, 520, 380, 100);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(280, 650, 180, 70);

        btnConfirmarMovimiento.setText("Confirmar Movimiento");
        btnConfirmarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarMovimientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmarMovimiento);
        btnConfirmarMovimiento.setBounds(60, 650, 180, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {
        try{ 
        
        String mesStr = (String) this.cmbMes.getSelectedItem();
        int mes = Integer.parseInt(mesStr);
        
                
        Area destino = this.lstAreaDestino.getSelectedValue();
        Empleado emp = this.lstEmpleados.getSelectedValue();
        
                     
        
        if (this.modelo.moverEmpleado(mes, emp, destino)) {
            JOptionPane.showMessageDialog(
                this,
                "El movimiento fue realizado con éxito.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
            
            
            
            }
        }catch(ExcepcionesSistema e){
                    JOptionPane.showMessageDialog(
                this,
                "Error"+e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
                    }
        
        }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
         JOptionPane alerta = new JOptionPane();
       int seleccion = alerta.showConfirmDialog(this,"Desea cancelar?", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
       
       if(seleccion == alerta.YES_OPTION){
           this.dispose();
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lstAreaOrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAreaOrigenMouseClicked
        Area a = (Area)this.lstAreaOrigen.getSelectedValue();        
        this.lstEmpleados.setListData(this.modelo.getEmpleadosPorArea(a).toArray(new Empleado[0]));
        
      
    }//GEN-LAST:event_lstAreaOrigenMouseClicked

    private void lstEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEmpleadosMouseClicked
         if(this.lstEmpleados.getSelectedIndex() >= 0 ){
            Empleado e = (Empleado)this.lstEmpleados.getSelectedValue();
            this.lstAreaDestino.setListData(this.modelo.listarAreasQueNoTenganEmpleado(e).toArray(new Area[0]));
        }
    }//GEN-LAST:event_lstEmpleadosMouseClicked

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarMovimiento;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<Area> lstAreaDestino;
    private javax.swing.JList<Area> lstAreaOrigen;
    private javax.swing.JList<Empleado> lstEmpleados;
    // End of variables declaration//GEN-END:variables
}
