/*
TRABAJO REALIZADO POR ESTEBAN NECUSE 227582 Y MARCOS MEDINA 365070
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas.areas;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ExcepcionesSistema;

import modelo.Sistema;

/**
 *
 * @author Byakogollo
 */
public class VentanaAltaArea extends javax.swing.JDialog {
    private Sistema modelo;
    /**
     * Creates new form VentanaAltaArea
     */
    public VentanaAltaArea(){
        initComponents();
    }
    public VentanaAltaArea(java.awt.Frame parent, boolean modal, Sistema modelo) {
       super(parent, modal);
       this.modelo = modelo;
       
        initComponents();
        this.cargarTabla();
        
    }
    
    private void cargarTabla(){
                       
               
                DefaultTableModel table = (DefaultTableModel) tblAreas.getModel();
                table.setRowCount(0);
                for(int i = 0; i<this.modelo.getAreas().size(); i++){
                                    
                
                table.insertRow(0,new Object[] {
                    this.modelo.getAreas().get(i).getNombre(),
                    this.modelo.getAreas().get(i).getPresupuestoAnual(),
                    this.modelo.getAreas().get(i).getEmpleados().size(),
                                        
                });
                
                
    }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblPresupuesto = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        spnPresupuesto = new javax.swing.JSpinner();
        lblAreas = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAgregarArea = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAreas = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Alta Areas");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(150, 30, 180, 80);

        lblPresupuesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPresupuesto.setText("Presupuesto (USD)");
        getContentPane().add(lblPresupuesto);
        lblPresupuesto.setBounds(50, 190, 120, 20);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombre del Area");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(50, 150, 130, 20);

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripcion");
        getContentPane().add(lblDescripcion);
        lblDescripcion.setBounds(50, 230, 90, 20);
        getContentPane().add(spnPresupuesto);
        spnPresupuesto.setBounds(190, 190, 210, 26);

        lblAreas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAreas.setText("Areas");
        getContentPane().add(lblAreas);
        lblAreas.setBounds(40, 350, 37, 20);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(280, 290, 110, 50);

        btnAgregarArea.setText("Agregar Area");
        btnAgregarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAreaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarArea);
        btnAgregarArea.setBounds(110, 290, 110, 50);
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(190, 230, 210, 24);

        tblAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Presupuesto (USD)", "Empleados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAreas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 380, 410, 110);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(190, 150, 210, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAreaActionPerformed
        
        try{
                                      
            if(this.modelo.altaArea(this.txtNombre.getText(), this.txtDescripcion.getText() , (Integer)this.spnPresupuesto.getValue())){
                JOptionPane.showMessageDialog(null, "Area guardada con exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
                
                this.txtNombre.setText("");
                this.txtDescripcion.setText("");
                this.spnPresupuesto.setValue(0);
                this.modelo.ordenarAreasPorNombre();
                this.cargarTabla();
            }
        }catch(ExcepcionesSistema e){
                    JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarAreaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
          JOptionPane alerta = new JOptionPane();
       int seleccion = alerta.showConfirmDialog(this,"Desea salir?", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
       
       if(seleccion == alerta.YES_OPTION){
           this.dispose();
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArea;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAreas;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPresupuesto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSpinner spnPresupuesto;
    private javax.swing.JTable tblAreas;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
