/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas.areas;


import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Area;

import modelo.Sistema;

/**
 *
 * @author Byakogollo
 */
public class VentanaModificarDescripcion extends javax.swing.JDialog {
    private Sistema modelo;
    /**
     * Creates new form VentanaAltaArea
     */
    public VentanaModificarDescripcion(){
        initComponents();
    }
    public VentanaModificarDescripcion(java.awt.Frame parent, boolean modal, Sistema modelo) {
       super(parent, modal);
       this.modelo = modelo;
        initComponents();
        this.cargarTabla();
        
    }
    
    private void cargarTabla(){
                       
               
                DefaultTableModel table = (DefaultTableModel) tblAreas.getModel();
                table.setRowCount(0);
                for(int i = 0; i<this.modelo.getAreas().size(); i++){
                                    
                
                table.insertRow(0,new Object[] {
                    this.modelo.getAreas().get(i).getNombre(),
                    this.modelo.getAreas().get(i).getPresupuestoAnual(),
                    this.modelo.getAreas().get(i).getEmpleados().size(),
                    this.modelo.getAreas().get(i).getDescripcion()
                                        
                });
                
                
    }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnModificarArea = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAreas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Modificar Area");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(320, 30, 260, 80);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(500, 370, 250, 50);

        btnModificarArea.setText("Modificar Descripcion");
        btnModificarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAreaActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarArea);
        btnModificarArea.setBounds(130, 370, 250, 50);

        tblAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Presupuesto (USD)", "Empleados", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAreas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 140, 800, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAreaActionPerformed
        
               DefaultTableModel tabla = (DefaultTableModel) this.tblAreas.getModel();
          int index = this.tblAreas.getSelectedRow();
           if(index >= 0){
               
          String nom = (String)this.tblAreas.getValueAt(index, 0);
         
          Area a = this.modelo.buscarAreaPorNombre(nom);
          
          VentanaConfirmarModificacionDescripcion v = new VentanaConfirmarModificacionDescripcion(this, true,a);
          
           v.setDefaultCloseOperation(v.DISPOSE_ON_CLOSE);
           v.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e){
                cargarTabla();
                
            }
        });
          v.setBounds(0,0,500,500);
          v.setLocationRelativeTo(this);
          v.setVisible(true);
           }else{
               JOptionPane.showMessageDialog(null, "Seleccione el area a modificar", "Error", JOptionPane.ERROR_MESSAGE);
           }
    }//GEN-LAST:event_btnModificarAreaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
          JOptionPane alerta = new JOptionPane();
       int seleccion = alerta.showConfirmDialog(this,"Desea salir?", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
       
       if(seleccion == alerta.YES_OPTION){
           this.dispose();
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificarArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblAreas;
    // End of variables declaration//GEN-END:variables
}
