/*
TRABAJO REALIZADO POR ESTEBAN NECUSE 227582 Y MARCOS MEDINA 365070
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas.areas;


import javax.swing.JOptionPane;

import modelo.Area;



/**
 *
 * @author Byakogollo
 */
public class VentanaConfirmarModificacionDescripcion extends javax.swing.JDialog {
    private Area area;
    /**
     * Creates new form VentanaAltaArea
     */
    public VentanaConfirmarModificacionDescripcion(){
        initComponents();
    }
    public VentanaConfirmarModificacionDescripcion(java.awt.Dialog parent, boolean modal, Area a) {
       super(parent, modal);
       this.area = a;
       initComponents();
       this.lblDescripcionActual.setText(this.area.getDescripcion());
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        lblNuevaDescripcion = new javax.swing.JLabel();
        txtDescripcionNueva = new javax.swing.JTextField();
        lblDescripcionActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Descripcion");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(150, 30, 210, 80);

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripcion actual");
        getContentPane().add(lblDescripcion);
        lblDescripcion.setBounds(50, 130, 120, 20);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(310, 310, 110, 50);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar);
        btnConfirmar.setBounds(70, 310, 110, 50);

        lblNuevaDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNuevaDescripcion.setText("Nueva Descripcion");
        getContentPane().add(lblNuevaDescripcion);
        lblNuevaDescripcion.setBounds(50, 220, 113, 20);
        getContentPane().add(txtDescripcionNueva);
        txtDescripcionNueva.setBounds(190, 220, 210, 22);

        lblDescripcionActual.setText("a");
        getContentPane().add(lblDescripcionActual);
        lblDescripcionActual.setBounds(200, 120, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
        if(!this.txtDescripcionNueva.getText().isBlank()){
            
                this.area.setDescripcion(this.txtDescripcionNueva.getText());
                JOptionPane.showMessageDialog(null, "La descripcion fue modificada","Descripcion modificada",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                            
        }else{
            JOptionPane.showMessageDialog(null, "La nueva descripcion no puede estar vacia","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
          JOptionPane alerta = new JOptionPane();
       int seleccion = alerta.showConfirmDialog(this,"Desea cancelar?", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
       
       if(seleccion == alerta.YES_OPTION){
           this.dispose();
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcionActual;
    private javax.swing.JLabel lblNuevaDescripcion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDescripcionNueva;
    // End of variables declaration//GEN-END:variables
}
