/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author jacqu
 */
public class VentanaInicial extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(VentanaInicial.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaInicial() {
        initComponents();
        setTitle("ERP - Inicio");
        setLocationRelativeTo(null);

        // F1: abrir ventana de autores
        getRootPane().getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW)
                .put(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0), "mostrarAutores");
        getRootPane().getActionMap().put("mostrarAutores", new javax.swing.AbstractAction() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                new ventanas.VentanaIntegrantes().setVisible(true);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnDemoSistema = new javax.swing.JButton();
        btnSistemaNuevo = new javax.swing.JButton();
        btnResumirSistema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VentanaInicial");
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Inicializacion");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(210, 30, 216, 40);

        btnDemoSistema.setText("Demo del Sistema");
        btnDemoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemoSistemaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDemoSistema);
        btnDemoSistema.setBounds(420, 110, 170, 40);

        btnSistemaNuevo.setText("Nuevo Sistema");
        btnSistemaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSistemaNuevo);
        btnSistemaNuevo.setBounds(40, 110, 170, 40);

        btnResumirSistema.setText("Resumir Sistema");
        btnResumirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumirSistemaActionPerformed(evt);
            }
        });
        getContentPane().add(btnResumirSistema);
        btnResumirSistema.setBounds(230, 110, 170, 40);

        setBounds(0, 0, 646, 232);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDemoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemoSistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDemoSistemaActionPerformed

    private void btnResumirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumirSistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResumirSistemaActionPerformed

    private void btnSistemaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaNuevoActionPerformed
        new ventanas.sistemaNuevo.VentanaPrincipalSistemaNuevo().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSistemaNuevoActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDemoSistema;
    private javax.swing.JButton btnResumirSistema;
    private javax.swing.JButton btnSistemaNuevo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
