/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author jacqu
 */
public class VentanaIntegrantes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaIntegrantes.class.getName());

    /**
     * Creates new form VentanaIntegrantes
     */
    public VentanaIntegrantes() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMarcos = new javax.swing.JLabel();
        lblEsteban = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VentanaIntegrantes");
        getContentPane().setLayout(null);

        lblMarcos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMarcos.setText("Marcos Medina - 365070");
        getContentPane().add(lblMarcos);
        lblMarcos.setBounds(50, 110, 240, 20);

        lblEsteban.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEsteban.setText("Esteban Necuse - 227582");
        getContentPane().add(lblEsteban);
        lblEsteban.setBounds(430, 110, 230, 20);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Trabajo Desarrollado Por");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(210, 20, 350, 40);
        getContentPane().add(lblLogo);
        lblLogo.setBounds(290, 80, 140, 90);
        ImageIcon icono = new ImageIcon("./img/logo.png");
        Image img = icono.getImage();
        Image newimg = img.getScaledInstance(120,120,java.awt.Image.SCALE_SMOOTH);
        icono = new ImageIcon(newimg);

        lblLogo.setIcon(icono);

        setBounds(0, 0, 729, 233);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaIntegrantes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEsteban;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMarcos;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
